#!/usr/bin/php
<?php

$snapFolder = "/.snap/";
$backupFolder = "/backup/";

$list = glob($snapFolder."/*");

sort($list);

$snapName = array_shift($list);

$snapName = explode('/',$snapName);
$snapName = array_pop($snapName);

$exe = "btrfs send {$snapFolder}/{$snapName} > {$backupFolder}/{$snapName}.btrfs";

`{$exe}`;
